### ISSUE TITLE
As a user, I want to view permits in groupings of required and conditionally required

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#101]
## Steps to Reproduce

1. After clicking on business type, the permits should be displayed in two groupings.
2. First grouping should be "required."
3. The second grouping, below the first, should be "conditionally required."

**Comment by Bjorn248** [comment]
This should be complete, will await final sign off from @samanthawolfe

**Comment by samanthawolfe** [comment]
Yep!
