### ISSUE TITLE
Add third button for online submission of permits

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#105]
## Steps to Reproduce

1. Next to view and download buttons, add a pencil type icon for permits that have an option for submitting online

## Actual Behavior

(Explain what actually happens.)

**Comment by samanthawolfe** [comment]
Added new column, Online Submission, in permit table dataset.

**Comment by Bjorn248** [comment]
@samanthawolfe there should be another column with the URL for the online submission right? Two new columns?
