### ISSUE TITLE
wireframes and/or composites for static content pages

### ISSUE THREAD

**Issue by gotoplanb** [codegnv/business-web#106]
- Each page is going to just be a components with some content.
- Nav bar is like trailhead with circle and active page larger circle
- Splash page is big image of a store, "open for business", and CTA to the first step.
- Samantha has all the content

**Comment by gotoplanb** [comment]
Duplicate of #14

**Comment by Bjorn248** [comment]
Links to resources provided by @samanthawolfe https://docs.google.com/document/d/1Sjo6M_F81wyHLzpaXwRcxQNgfSk4WaH6pyM0Nw8aJ0A/edit?usp=sharing
