### ISSUE TITLE
Make sure business type name is above the permits list

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#107]

**Comment by ajcrites** [comment]
@Bjorn248 can this be closed?

**Comment by Bjorn248** [comment]
@hollymariegibbs can you add the comp with the `Required:` that we talked about?

**Comment by Bjorn248** [comment]
Comps: https://www.dropbox.com/sh/svm8d6u4gh8rsyd/AABkdsAkiWVaZMaoF01YuEhta?dl=0&preview=Filter+Results.png

https://www.dropbox.com/sh/svm8d6u4gh8rsyd/AABkdsAkiWVaZMaoF01YuEhta?dl=0&preview=Form+directory.png

https://www.dropbox.com/sh/svm8d6u4gh8rsyd/AABkdsAkiWVaZMaoF01YuEhta?dl=0&preview=Home.png

https://www.dropbox.com/sh/svm8d6u4gh8rsyd/AABkdsAkiWVaZMaoF01YuEhta?dl=0&preview=Search+Results.png
