### ISSUE TITLE
Complete links for Footer

### ISSUE THREAD

**Issue by ajcrites** [codegnv/business-web#112]
Update these footer links"

* [x] Disclaimer
* [x] Privacy Policy
* [x] Accessibility

Move a couple header links to the footer and also make 'em go somewhere:

* [x] About
* [x] Contact

Also the email icon directs to the contributing guidelines but it should probably be used for some method of contact.

**Comment by samanthawolfe** [comment]
@ajcrites @hollymariegibbs Do you guys need me to provided language/content for these three portions of the site? Here are some resources we developed for the dataGNV site, the open data portal. If you this is what you're looking for I work to develop something unique for this site. Accessibility - https://data.cityofgainesville.org/accessibility. Privacy Policy - https://data.cityofgainesville.org/privacy.

**Comment by hollymariegibbs** [comment]
We should be able to copy/paste directly from those sites unless they have site-specific content?

**Comment by samanthawolfe** [comment]
@hollymariegibbs & @Bjorn248 See links above. We can either directly link to these pages on the data portal or duplicate the pages on new pages on the business portal.
