### ISSUE TITLE
Clean up data in Socrata

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#12]
@ambercabrera @samanthawolfe let's get together during the next meeting and knock this out

The main items for me are as follows
1. Make column titles in business types table the "permit_name". The friendly name is stored in the permits table, Socrata does the transformation right now so let's just make the column title what we'll be consuming anyway to avoid duplication and confusion. The column title should be the value of "permit_name" from the permits table.
2. Look at the latest data sets that you have from the city and see if we can represent it in Socrata. You mentioned that there were about 150 business types, but only ~60 are represented in Socrata.

The data ingestion portion is complete (as of Thursday) so now we'll be relying on Socrata to be accurate so that the website can display up-to-date information.

**Comment by Bjorn248** [comment]
Also, we need more permits in the permits table, as right now there are only 3. Just adding it to this ticket so it is not forgotten.

**Comment by ambercabrera** [comment]
A quick update... the permit table is complete and can find it here - https://data.cityofgainesville.org/Economic-Development-Redevelopment/Permit-Table/pmwr-qvc6

Next thing to do is to update the names in the business types table. I'll finish that at the next event or before then. Almost done!

**Comment by Bjorn248** [comment]
Great progress on the new permit table today @samanthawolfe. Looking forward to seeing the permits table get the same kind of love!

**Comment by Bjorn248** [comment]
@samanthawolfe I found a duplicate category. "General Service" vs "General Services". You can see it on the live dev site now.
