### ISSUE TITLE
Display count of Required and Conditionally Required Permits

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#123]
We just want to match the visual comps at this point.

**Comment by firoze** [comment]
Could you link up the comps as well? I can't find it 😞 I can work on this later

**Comment by Bjorn248** [comment]
@firoze haha I'm about to submit the PR for this :p

**Comment by firoze** [comment]
@Bjorn248 Oh nice!! Carry right on, then!

**Comment by Bjorn248** [comment]
@firoze #37 is the original issue with the comps
