### ISSUE TITLE
Make TurboTax inspired workflow 

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#125]
TurboTax has a really great workflow for going through your taxes. We could probably come up with something similar for the business portal. The main themes are breaking the workflow down into sections and having guiding questions along the way with resources to help people get the answers they need even if they don't know the answer initially.

**Comment by Bjorn248** [comment]
Apparently Credit Karma has a similar service as well.

**Comment by ajcrites** [comment]
Wat?

**Comment by Bjorn248** [comment]
Also, [opencounter](https://opencounter.com/) uses a similar system of questions to guide a user through the workflow.
