### ISSUE TITLE
Add Next Step Section

### ISSUE THREAD

**Issue by jgardner34** [codegnv/business-web#131]
## Expected Behavior
Matching this comp, a Next Steps section appears under the search results with a link to booking a appointment with the Department of Doing.

https://www.dropbox.com/sh/svm8d6u4gh8rsyd/AABkdsAkiWVaZMaoF01YuEhta?dl=0&preview=Filter+Results.png

## Actual Behavior
Only search results appear

**Comment by gotoplanb** [comment]
:shipit:
