### ISSUE TITLE
Add Landing Page

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#133]
Landing page or a splash screen that resembles a storefront with glass windows with a "Welcome, we're open!" type of sign. 
![image](https://cloud.githubusercontent.com/assets/19419412/23732569/d11629ac-0441-11e7-8f76-1349a462abc9.png) 
![image](https://cloud.githubusercontent.com/assets/19419412/23732578/dcee63a2-0441-11e7-85f8-a68e2b1d66de.png)

**Comment by samanthawolfe** [comment]
Here's another example minus the bubbles
![capture 2](https://cloud.githubusercontent.com/assets/19419412/24016988/a4492716-0a64-11e7-8a8f-60a7b363ec0d.PNG)

**Comment by samanthawolfe** [comment]
@Bjorn248 Should this go to you, @gotoplanb or @ajcrites? Thanks!!

**Comment by Bjorn248** [comment]
It should go to a designer? I think there was some hesitation on my part to add a screen that we didn't find as useful as others. I'm personally fine adding anything to the site and relying on user feedback to tell us if it's good/bad, but the fact that we need a designer that can lead a central design vision forward remains true.

**Comment by gotoplanb** [comment]
Chatted with Firoze. At least to get the stuff working:

* [x] Add a home view
* [x] Add a home route
* [x] Insert this photo
* [x] Clicking photo goes to step 1 route
* [x] Set default route to load home route
* [x] Clicking logo sends to home route

**Comment by gotoplanb** [comment]
@samanthawolfe We now have the start of a landing/home page. It's just an image for now that you can see at http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/#/home

I'm closing this current issue for setting up the home screen, but please do open an additional issue if you have ideas for what should be on the landing page.
