### ISSUE TITLE
Cannot refresh site

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#136]
## Steps to Reproduce

1. Load the s3 site [http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/](http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/)
2. Refresh

## Expected Behavior

Site refreshes

## Actual Behavior

404 Not Found

I think this has to do with routes. Might have to change how angular 2 does routing. [https://angular.io/docs/ts/latest/guide/router.html#!#-hashlocationstrategy-](https://angular.io/docs/ts/latest/guide/router.html#!#-hashlocationstrategy-)

**Comment by ajcrites** [comment]
Another possibility: redirects for S3: http://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html
