### ISSUE TITLE
Clarify Conditionally Required Permits

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#140]
How do we communicate to the user if the conditionally required permit is relevant to them?

We need plain language / easy to understand descriptions for each condition. Also, is this relevant to permits themselves or just the business type + permit combination? 

We are trying to determine how to display this information so that it is useful to the user. What does it mean to be conditionally required? Need clarity here.

**Comment by samanthawolfe** [comment]
Working to include a general description of why a permit is conditional, like the building permit app and home occupational licenses examples already included.
