### ISSUE TITLE
Match visual comp for permit locator

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#141]
## Steps to Reproduce

1. Open permit locator

## Expected Behavior

Screen should look similar to https://www.dropbox.com/s/tbya202s37ydwi7/Form%20directory.png?dl=0. Note the following discrepancies
Find specs here: https://www.dropbox.com/sh/zisrb2jlew4jyru/AACf9LvWyg0pRLjc60K-9gtla/business-web/design?dl=0
1. "FORMS TO LAUNCH YOUR BUSINESS"
2. "Required Permits: <Business Type Name> (Number)" how the Number is a lighter style
3. Only 25 business types are listed on the left, with the option to "View more results" which expands to all business types

## Actual Behavior

See live site. This is what it currently looks like (not matching comps)
![screenshot-localhost-8080 2017-03-21 19-23-55](https://cloud.githubusercontent.com/assets/1063707/24175327/f93aec04-0e6b-11e7-98c5-c464cc76397d.png)

**Comment by Bjorn248** [comment]
Now that is cool ^

**Comment by Bjorn248** [comment]
@hollymariegibbs we need the svg for the business portal logo included in the linked comp, I can't seem to find it.

**Comment by Bjorn248** [comment]
@gotoplanb here's the SVG issue

**Comment by gotoplanb** [comment]
@Bjorn248 I'm having trouble making the SVG right quickly -- fonts aren't being drawn correctly. Here are PNGs in case you need/want to keep moving. I'll try again with the fonts tomorrow.

![logo--business-portal](https://cloud.githubusercontent.com/assets/51855/24435726/0c790136-1405-11e7-9a29-c50514fa8ce0.png)

![logo--business-portal 2x](https://cloud.githubusercontent.com/assets/51855/24435727/0c7a0bf8-1405-11e7-875d-b7f41fc80563.png)

**Comment by Bjorn248** [comment]
Still need to get it so that you can deselect a business type once it's selected (I broke this somehow). Also need to center the logo and the separation line below in the header (see comp). Feature branch should be referenced directly above this comment.

**Comment by gotoplanb** [comment]
:shipit:
