### ISSUE TITLE
Add plain-text description to each permit in Socrata data set

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#142]
Almost every permit has "Test description of permit", e.g. "Development Plan Review". Before we can launch, each permit needs a plain-text description so the user knows what each permit is for.

**Comment by gotoplanb** [comment]
@samanthawolfe Nudge nudge. This isn't blocking us from working, but we'll need to spend some time collectively poking all the site with a stick to see what content needs to be updated in prep for golive.
