### ISSUE TITLE
Design search results view

### ISSUE THREAD

**Issue by hollymariegibbs** [codegnv/business-web#143]
Need to display the following:
- Term the user searched for
- Relevant permits
- Relevant Business Types
- What happens once the user selects a result? Do they lose the search results?

**Comment by Bjorn248** [comment]
Another thing we might want to think about is that so far we've only had the flow for "selecting" a business type. Selecting a Permit has never happened, and we don't have the visuals for that kind of flow either.

**Comment by samanthawolfe** [comment]
Can we REFINE YOUR RESULTS by Business Types and PERMIT NAME? With both being some type of drop-down or smaller scrolling box, rather than a long list?

![image](https://user-images.githubusercontent.com/19419412/30345177-253bbae6-97d2-11e7-93f3-fdf4f865a8e0.png)
