### ISSUE TITLE
Make it so that only one business type can be selected at a time

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#144]
This was the original functionality and our UX designer has laid down the hammer saying that more than one business type should not be selectable at once.

**Comment by Bjorn248** [comment]
This is somewhat addressed in #141 but there's currently a regression where the business type cannot be deselected.

**Comment by ajcrites** [comment]
@Bjorn248 do we still want to do this?

**Comment by gotoplanb** [comment]
@ajcrites Yeah seems like a good thing to at least try to fix if it's doable in an evening.
