### ISSUE TITLE
Evaluate existing data structure returned by service layer

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#15]
Currently it is a `BusinessCategory[]` but if we are required to do lookups on categories to get business types, or business types to get permits, we will have to change the data structure to an object where the keys are the names of business categories, types, and permit names and the values are objects whose keys are the values we want returned. 

Another option would be to add a function that takes the original data structure and creates a lookup object from it instead of the lookup object being returned from the service layer.

This assumes that lookup functions will be required by the frontend. If they are not required, then this is not relevant.

**Comment by ragafoo** [comment]
worked a bit more on the the learning styling and animations in angular2, I think the BusinessListComponent is fine for the front end https://github.com/ragafoo/business-web/tree/frontend_start

**Comment by Bjorn248** [comment]
Yep, reviewed with @ajcrites and it's fine, for now.
