### ISSUE TITLE
As a user, when I click on a business category, I want to see a list of associated business types

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#16]
e.g. When I click on `Manufacturing` I want to see `Brewery, Microbrewery and IPA` as it is a business type of that category. Keep in mind the data structure returned by the service layer is given in the sample json here: https://gist.github.com/ajcrites/529279f9fc29aef46e1a1480c7c16385

**Comment by ajcrites** [comment]
Is this done?
