### ISSUE TITLE
Content for routes linked from footer

### ISSUE THREAD

**Issue by gotoplanb** [codegnv/business-web#162]
We'll want some reasonable content at these routes before we go live:

* [x] About
* [x] Contact
* [x] Disclaimer

**Comment by gotoplanb** [comment]
@samanthawolfe Currently we have no content for these three pages. Let me know if you want any of these removed. Please paste in this here issue any content you'd like us to put on these pages (or links where you want them to go).

**Comment by samanthawolfe** [comment]
Let's remove GET ASSISTANCE. I think this content will be well covered in each step of the business process.

**Comment by samanthawolfe** [comment]
ABOUT - Let's move the current ABOUT THIS SITE in the footer to the ABOUT page. Also, let's include the Github links and contributions guidelines on the ABOUT page.
![image](https://user-images.githubusercontent.com/19419412/30344444-53ff5c3c-97cf-11e7-98d6-7bb8a8ef9dbf.png)
![image](https://user-images.githubusercontent.com/19419412/30344451-599fa962-97cf-11e7-961a-36056ac62d84.png)

**Comment by samanthawolfe** [comment]
CONTACT - Change to NEXT STEPS.
Content:

- SCHEDULE A FIRST-STEP APPOINTMENT WITH THE DEPARTMENT OF DOING (remove the Next Steps section at the end of each permit search result; add to new centralized page)
![image](https://user-images.githubusercontent.com/19419412/30344618-0b5d088e-97d0-11e7-8575-1b2a7abec4e2.png)

- TALK WITH THE ECONOMIC DEVELOPMENT DIRECTOR
Erik Bredfeldt, Pd.D.
Telephone: 352-393-8614
Email: bredfeldea@cityofgainesville.org

- CHAT WITH A CITY PLANNER
http://www.cityofgainesville.org/PlanningDepartment.aspx
Can we embed the Zendesk add-in like on Planning's webpage?
![image](https://user-images.githubusercontent.com/19419412/30344745-8a127218-97d0-11e7-9293-cc2c4543f63b.png)

**Comment by samanthawolfe** [comment]
DISCLAIMER - Remove
TERMS OF SERVICE - Should we create something like this (https://socrata.com/terms-of-service/)?
ACCESSIBILITY - Is this applicable to this site (https://socrata.com/accessibility/)? Can anyone help determine if the business portal will be accessible?
PRIVACY POLICY - Can we create a new page on the business portal and copy this info (https://data.cityofgainesville.org/privacy)? Can anyone help verify it correctly represents the biz portal?

**Comment by samanthawolfe** [comment]
General idea is for a simpler, smaller footer.
