### ISSUE TITLE
Content for various pages

### ISSUE THREAD

**Issue by gotoplanb** [codegnv/business-web#166]
![6707ee32-f821-11e6-9040-1daf8b8a90dc](https://cloud.githubusercontent.com/assets/51855/26130953/2cac3e74-3a65-11e7-9134-1f257addfd95.png)

Let's put the content in this here issue as comment. Just start a new comment for each page (e.g. Dream) and then paste in the text, images, URLs, etc that we should include.

* [x] Dream
* [x] Plan
* [x] Finance
* [x] Legalize
* [x] Brand
* [x] Search
* [x] Shape
* [ ] Build
* [ ] Hire
* [ ] Taxes
* [ ] Celebrate
* [ ] Open
* [ ] Grow

**Comment by samanthawolfe** [comment]
SEARCH content page - https://docs.google.com/document/d/1UVAt1Xb2H1kO7zKT9fbmTk_-XPcJ32d6mZ2U878-FYM/edit?usp=sharing

Should be routed to the Zoning Portal website here: https://zoning.cityofgainesville.org/. Is it possible to have an easy connection/link back to the Business Portal?

**Comment by samanthawolfe** [comment]
Shape - Should be the Permit Locator. We are ok with calling it Permits or something similar, rather than Shape.

**Comment by Bjorn248** [comment]
Remember to see the current state of affairs here http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/#/home. As you can see,  Shape and Permit are two separate things according to the current live site. So the instruction here is to get rid of "Shape" and just move "Permit" to take its place?

**Comment by samanthawolfe** [comment]
Yes, "Permit" should be "Shape".

**Comment by samanthawolfe** [comment]
Master Working Document
https://docs.google.com/document/d/1WFz1_CpWq5nvWQFSf8coM3WozEDtIwkkZrFuE6AHMxA/edit?usp=sharing

**Comment by samanthawolfe** [comment]
I'll post individual documents for each finalized content page

**Comment by samanthawolfe** [comment]
Content page design mock-up
![finance mobile](https://user-images.githubusercontent.com/19419412/31193836-3d0364ba-a913-11e7-8d96-37d14d23595a.png)
![finance](https://user-images.githubusercontent.com/19419412/31193837-3d04198c-a913-11e7-813f-617bb8705e43.png)
![hire mobile](https://user-images.githubusercontent.com/19419412/31193839-3d086032-a913-11e7-8f33-49f59f6d995e.png)
![pop out menu](https://user-images.githubusercontent.com/19419412/31193838-3d072ae6-a913-11e7-953a-ab3710ad7e04.png)
![search mobile](https://user-images.githubusercontent.com/19419412/31193842-3d517204-a913-11e7-8e9c-cac74df9a568.png)
![dream mobile](https://user-images.githubusercontent.com/19419412/31193841-3d103992-a913-11e7-85eb-48cc534ea5ea.png)
![dream](https://user-images.githubusercontent.com/19419412/31193840-3d0d2978-a913-11e7-8f43-8c86e6b4f91f.png)
[Style Guide - Page Blueprints.pdf](https://github.com/c4gnv/business-web/files/1357007/Style.Guide.-.Page.Blueprints.pdf)

**Comment by samanthawolfe** [comment]
DREAM content page - https://docs.google.com/document/d/1g0WcuXJ44AlYwsuKBq_Maa7fwJ0GzEbkDaBtNjmpqxg/edit?usp=sharing

**Comment by samanthawolfe** [comment]
PLAN content page - https://docs.google.com/document/d/1FyuHk8BOgnjSGRsBy5ILJAldfRjE408S6-8frikFpZ4/edit?usp=sharing

**Comment by samanthawolfe** [comment]
FINANCE content page - https://docs.google.com/document/d/1TWOJBA8XQKqfsRrIJ_O_aUO6ROBKFUe3Cy67r_Y99hM/edit?usp=sharing

**Comment by samanthawolfe** [comment]
LEGALIZE content page - https://docs.google.com/document/d/1GKSRgwKO7lyFDZdRIXttQHxGALyANetLtoo0cKkqRCM/edit?usp=sharing

**Comment by samanthawolfe** [comment]
BRAND content page - https://docs.google.com/document/d/1hsIYSrImjRnUgSNvKG0d9WbczbLMy46MbefmRybus0Q/edit?usp=sharing
