### ISSUE TITLE
Add business description column to the open data portal

### ISSUE THREAD

**Issue by gotoplanb** [codegnv/business-web#168]
It would be super lovely to be able to have a 1- to 3-sentence description of a business to be able to show on the permit locator.

@samanthawolfe Can you add this column to the open data portal, or show me how to do it?

**Comment by samanthawolfe** [comment]
Yep, can do @gotoplanb. Can you give me an example of what you're thinking? Like a couple sentences for every business type?

**Comment by gotoplanb** [comment]
@samanthawolfe Totally copying from Wikipedia just to give an example of what I'm thinking for a business description:

"An assisted living residence or assisted living facility (ALF) is a housing facility for people with disabilities or for adults who cannot or chose not to live independently. The term is popular in the United States but is similar to a retirement home in the sense that facilities provide a group living environment and typically cater to an elderly population." [source]

[source]: https://en.wikipedia.org/wiki/Assisted_living

**Comment by Bjorn248** [comment]
@samanthawolfe a column in this table should do the trick: [https://data.cityofgainesville.org/Economic-Development-Redevelopment/Permits-by-Business-Type/i9px-haju/data](https://data.cityofgainesville.org/Economic-Development-Redevelopment/Permits-by-Business-Type/i9px-haju/data). I can't seem to edit the data to add test descriptions. Perhaps a valid column title would be `business_description`.

**Comment by samanthawolfe** [comment]
New column added to this table: https://data.cityofgainesville.org/Strong-Economy/Permits-by-Business-Type/w5ec-qx4j/data. Description input in the third row (for Ad Agency) to test integration. Working to update other business types.
