### ISSUE TITLE
Infographic for Service Diagram

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#186]
Ideas:

- New visual design of the service diagram as an infographic.

- Central navigation, overview of all the pages a user can navigate on the site.

Expected Behavior:

- One page, scroll through diagram

[Style Guide - Page Blueprints.pdf](https://github.com/c4gnv/business-web/files/1357001/Style.Guide.-.Page.Blueprints.pdf)
![service diagram](https://user-images.githubusercontent.com/19419412/31193750-057ef072-a913-11e7-83bd-557a2d69ad71.png)

**Comment by kassidywallace** [comment]
Infographic/Portal Icons

- For use on all elements with icons

[Icons.zip](https://github.com/c4gnv/business-web/files/1326840/Icons.zip)
