### ISSUE TITLE
508 compliance fixes

### ISSUE THREAD

**Issue by gotoplanb** [codegnv/business-web#187]
http://wave.webaim.org/report#/http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/

**Comment by samanthawolfe** [comment]
@gotoplanb Would this address potential accessibility issues that may be caused by color-blindness? Someone from our marketing team also suggested running things through a color blind simulator like http://www.color-blindness.com/coblis-color-blindness-simulator/.

**Comment by gotoplanb** [comment]
@samanthawolfe Yep, we should definitely use a color-blindness simulator in the future. I'm not going to both with the current design, but we should do so as new design is implemented.

**Comment by jamessmell** [comment]
@stetsonjn thinking this is one to note as a good rule of thumb but can be closed. Can you confirm?

**Comment by stetsonjn** [comment]
Great tool! Yes, let's close.

**Comment by Opeola** [comment]
Hey all - FYI, there are folks still subscribed to these GitHub notifications that are long gone from the Gainesville scene! Removing myself, but just flagging that y'all may want to review who's on!
