### ISSUE TITLE
Homepage Redesign

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#188]
Homepage visual designs for desktop & mobile & style guide.

**Comment by kassidywallace** [comment]
Homepage Redesign Sketch + Assets

![desktop hd](https://user-images.githubusercontent.com/32228374/32015591-8367713a-b98f-11e7-8067-51a24613dd1d.png)

[Homepage Design 2.zip](https://github.com/c4gnv/business-web/files/1415713/Homepage.Design.2.zip)


Assets:
https://www.dropbox.com/s/x6yofuhnb1hg4l3/Homepage%20Assets.zip?dl=0

**Comment by jamessmell** [comment]
@stetsonjn is this still relevant?

**Comment by stetsonjn** [comment]
No. This is from the previous project.
