### ISSUE TITLE
broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tillydray** [codegnv/business-web#192]
https://github.com/c4gnv/business-web/projects/1 results in a 404. This link is in [Project Board](https://github.com/c4gnv/business-web/blob/develop/CONTRIBUTING.md#project-board). I don't know where to point the link otherwise I'd fix it myself.

**Comment by Bjorn248** [comment]
Oh that's strange, I wonder if github deprecated that feature. I'll ask around to figure out what happened. Maybe @gotoplanb knows?

**Comment by jamessmell** [comment]
@Bjorn248 can you let me know if this issue is still relevant or whether we can close it?

**Comment by Bjorn248** [comment]
@jamessmell This repo seems like it has been abandoned. I think we can close it.

**Comment by jamessmell** [comment]
Closing
