### ISSUE TITLE
Hovering over navbar items doesn't change cursor to pointer

### ISSUE THREAD

**Issue by tillydray** [codegnv/business-web#193]
## Steps to Reproduce

1. Go to http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/#/home
2. Hover over the navbar images
3. Cursor will not change to a pointer unless you hover over the text in the navbar item

## Expected Behavior

I expect my cursor to become a pointer when hovering over anything clickable.

## Actual Behavior

My cursor does not become a pointer when hovering over the clickable icons.

**Comment by tillydray** [comment]
I will work on this, it'll only take a minute, but I can't assign myself or anyone else otherwise I would.

**Comment by Bjorn248** [comment]
Should be a simple css fix, `cursor: pointer` for the element should do it right?

**Comment by ajcrites** [comment]
Yeah

**Comment by samanthawolfe** [comment]
Also, the same behavior occurs when hovering over of the Business Portal logo to return home.

**Comment by Bjorn248** [comment]
The original issue was fixed with https://github.com/c4gnv/business-web/pull/194, however, I will leave this open so we can address the issue @samanthawolfe pointed out as well.

**Comment by tillydray** [comment]
Working on it right now.

EDIT: Just made PR #200 to address what Samantha brought up.

**Comment by jgardner34** [comment]
This looks to be completed and 👍 , marking as closed
