### ISSUE TITLE
Improve navigation of filtering by business type in mobile version of Permit Locator

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#198]
## Steps to Reproduce

1. While visiting the mobile version, select a business type
2. Selected type turns bold & blue

## Expected Behavior

As when using the search bar, when selecting a business type, the remaining list should condense or disappear.

## Actual Behavior

The selected business type turns blue & bold, which is not clear to the user the selection was successful. User then has to scroll down to the bottom of the list of types to view document results.

**Comment by jamessmell** [comment]
@stetsonjn can you take a look at this one and let me know if its still relevant or whether we should close it?

**Comment by stetsonjn** [comment]
this is an old project from the previous brigade. We can close it.

**Comment by stetsonjn** [comment]
I can't close this.

**Comment by Bjorn248** [comment]
@stetsonjn @jamessmell You should both have permissions to manage these repos now.

**Comment by jamessmell** [comment]
Closing

**Comment by stetsonjn** [comment]
mwwahahahaha. i have the power now.
