### ISSUE TITLE
Add new users to Dropbox

### ISSUE THREAD

**Issue by samanthawolfe** [codegnv/business-web#199]
Please add wolfesb@cityofgainesville.org and WallaceKL@cityofgainesville.org to the Dropbox folder (https://www.dropbox.com/sh/zisrb2jlew4jyru/AACReOBxUmW6FY2ogxVFaAmVa?dl=0) for adding design content.

**Comment by Bjorn248** [comment]
I believe that was Holly's. Should we move to something else @gotoplanb?

**Comment by gotoplanb** [comment]
@Bjorn248 I suggest we enable the wiki repo for `business-web`, and then we keep assets there. What say you?

**Comment by Bjorn248** [comment]
Seems like a good plan to me

**Comment by samanthawolfe** [comment]
Sounds good to me. How do we navigate there to provide assets?

**Comment by gotoplanb** [comment]
@samanthawolfe There isn't a good visual interface for adding images to the wiki -- it requires us add files to some local folder then push up via git commands. The wiki will be a nice place for people to get/read files. For uploading new stuff, I think you should just upload via Slack, then either @Bjorn248  or I can shove into the wiki

**Comment by Bjorn248** [comment]
You can also upload images directly to issues

**Comment by samanthawolfe** [comment]
Kassidy has been working in Sketch and has some deliverables ready. Is through Slack still the best way? Or, should we set-up a new dropbox as it sounds like there will be layers of folders and assets.

**Comment by gotoplanb** [comment]
@samanthawolfe Let's go with Slack delivery for now. Going forward, we might consider using InVision since a) public share URLs, b) any contributor can invite other contributors, c) great handling of both mockups and raw assets, d) super interoperability with Sketch files.

**Comment by Bjorn248** [comment]
What's wrong with using issues? I guess slack or github is fine, but on github I don't think there are content limits?

**Comment by gotoplanb** [comment]
@Bjorn248 You can only (afaik) attach images to issues. You cannot attach `.sketch` files and other sorts of assets.

**Comment by gotoplanb** [comment]
@Bjorn248 I do agree though if the goal is to deliver specific images to resolve an issue, then GH Issues is the right way to go. If, however, we're trying to have longer-living design documentation, we'd need something else.

**Comment by Bjorn248** [comment]
@gotoplanb 
[Untitled.zip](https://github.com/c4gnv/business-web/files/1396182/Untitled.zip)

There's a sketch file inside there :p

**Comment by Bjorn248** [comment]
Looks like they support the following extensions: gif, jpeg, jpg, png, docx, gz, log, pdf, pptx, txt, xlsx, zip

**Comment by gotoplanb** [comment]
Oh awesome! This must be relatively new development! Okay, @samanthawolfe delivery via GH Issues inside a ZIP file please 😁

**Comment by samanthawolfe** [comment]
Will do! Thanks!
