### ISSUE TITLE
Make issue template only show up when bug is added as a label (is this possible?)

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#20]
We don't want the bug template to show up for all work that we do because issues are also used to track features/general work.

**Comment by ghost** [comment]
As far as I can tell, it's all or nothing. The docs are here: https://help.github.com/articles/helping-people-contribute-to-your-project/. I would suggest we remove the template if it's going to be a nuisance.

**Comment by Bjorn248** [comment]
Perhaps the template should just be modified to make it clear that it should only be used for new bug reports? I still feel like it contains useful information that shouldn't just be thrown out.
