### ISSUE TITLE
Homepage Design

### ISSUE THREAD

**Issue by hollymariegibbs** [codegnv/business-web#21]
Design the Business Permit portal homepage

**Notes:**
- Business Permit Locator (single page)
- Business Categories
- Business Types
- Permits

Category List > Business Type > Permit List

Permits have the following data:
- Friendly name
- URL
- Download or view capability

**Comment by hollymariegibbs** [comment]
Comps are here: https://www.dropbox.com/s/86f7walarvqrp2a/Search%20Results.png?dl=0

@Bjorn248 & @ragafoo can you please review and let me know if you need me to make any changes before I generate the specs?

**Comment by hollymariegibbs** [comment]
Maybe @gotoplanb can also take a look? Pretty please <3

**Comment by Bjorn248** [comment]
Seems fine to my untrained eye :p

**Comment by ragafoo** [comment]
This looks Great! thanks so much, i'm gonna start implementing this and then we can do some iteration from there.  Any objections?

**Comment by samanthawolfe** [comment]
Here are some additional graphics designed by IDEO, which may be helpful. Specifically, the planning department is being reorg'd as the "Department of Doing" and using the new logo.
https://www.dropbox.com/sh/xvlithxnpkwxvqi/AACOxkQHKU-9_rzxNRhPnqNZa?dl=0
https://www.dropbox.com/sh/xvlithxnpkwxvqi/AABtG8Ew0hXnD2s-_7adoZTna/04%20-%20Deliverables/02%20Branding%20Assets/Logo?dl=0

**Comment by hollymariegibbs** [comment]
@ragafoo let me know when you're ready for assets; I can put together a folder for you

**Comment by ragafoo** [comment]
Excellent, the next PR will have an assets/media folder, I'll use place holders and/or create some stuff in photoshop/illustrator based on your designs.

**Comment by hollymariegibbs** [comment]
@Ragafoo sketch file is here :) https://www.dropbox.com/s/yrmoyoxj0jzj6xr/business-portal.sketch?dl=0

**Comment by hollymariegibbs** [comment]
Homepage comp is here: https://www.dropbox.com/s/b4vcpak4dvqjux8/Home.png?dl=0
