### ISSUE TITLE
Department of Doing integration

### ISSUE THREAD

**Issue by hollymariegibbs** [codegnv/business-web#31]
From @samanthawolfe:

> Here are some additional graphics designed by IDEO, which may be helpful. Specifically, the planning department is being reorganized as the "Department of Doing" and using the new logo.
> https://www.dropbox.com/sh/xvlithxnpkwxvqi/AACOxkQHKU-9_rzxNRhPnqNZa?dl=0
> https://www.dropbox.com/sh/xvlithxnpkwxvqi/AABtG8Ew0hXnD2s-_7adoZTna/04%20-%20Deliverables/02%20Branding%20Assets/Logo?dl=0

Please let us know where we need to integrate this new content

**Comment by samanthawolfe** [comment]
@hollymariegibbs Ideas for incorporating:
1. Large logo incorporated onto homepage/search page banner on top of yellow background
   - To right of search box
   - In place of pencils
2. Small logo with text, “Ready to take your first step?” in top of header (replace About, Contact)
   - Link to set-up first step meeting with city http://www.cityofgainesville.org/PlanningDepartment/FirstStepAssistance.aspx
3. Next steps module below permit/form search results above footer
   - DoD logo w/ link to set-up first step meeting (above in 2)
   - Descriptive text: The Department of Doing will provide a convenient, one-stop location where business owners, developers, and other interested persons receive development and permitting information from several city departments at one time. This will be a convenient time for you to submit your permits and forms, learn more, and most importantly ask questions and receive support.

**Comment by samanthawolfe** [comment]
This is a great recent article. The use of language around the DoD may also be helpful. https://www.fastcodesign.com/3065107/slicker-city/how-one-florida-city-is-reinventing-itself-with-ux-design

"It will be a physical office, a one-stop shop for obtaining all the permits needed to open a business or develop real estate, as well as a web platform (both of which are still under development). The office will be staffed with a new kind of employee, Sherpa-like "action officers" which the city is now in the process of hiring."

**Comment by samanthawolfe** [comment]
Good placeholder header (First Steps) and descriptive text. PDS staff will be taking on a design sprint challenge to rebrand the meeting name/title and how it's communicated to the community. Our goal is to deliver by end of year, so timing will be good!

**Comment by hollymariegibbs** [comment]
"The Department of Doing provides a convenient, one-stop location where you can submit permits and forms, learn more about starting a business, ask questions and receive support. The office staffs employees that are actionable guides who help you throughout the process."

**Comment by samanthawolfe** [comment]
@hollymariegibbs Very nice! Can we conclude with a call to action of setting up a next steps appt to (1) review/submit docs/permits and (2) review zoning options?

**Comment by hollymariegibbs** [comment]
@samanthawolfe is it too casual to refer to someone at the Department of Doing as a 'Do-er'?

**Comment by samanthawolfe** [comment]
No, I don't think so but will you provide the context?

**Comment by samanthawolfe** [comment]
I saw the preview and it looks amazing! They are calling do-er's "Action Officers" so that may work better.

**Comment by hollymariegibbs** [comment]
cc @ajcrites

**Comment by ajcrites** [comment]
@hollymariegibbs can you link directly to the designs for the updated header when they are ready?

**Comment by hollymariegibbs** [comment]
no

**Comment by gotoplanb** [comment]
@ajcrites We added in the newer header with that sweet, sweet blue house. Also moved the "next steps thing" to the bottom of permit locator view. We probably should be adding this to the bottom of some other steps as well.

:shipit:
