### ISSUE TITLE
Create a list of resources, link, sponsors, etc. to be included on site

### ISSUE THREAD

**Issue by hollymariegibbs** [codegnv/business-web#32]
We need a final + approved list of all businesses and organizations to link to from the Business Portal site, as well as any other information that needs to be included. The content in the footer is basically a compilation of things I found around existing sites and sample sites and was cobbled together.

**Comment by samanthawolfe** [comment]
- [x] New text above search box

GNV is open for business!
Locate permits, licenses, and forms by searching or filtering below.
- [x] Edit "Permits" header

Forms To Launch Your Business
- [ ] New City logo in footer

![ideo blue city gnv_logo converted](https://cloud.githubusercontent.com/assets/19419412/19912138/c3b7e232-a06e-11e6-9782-9056430e8d11.jpg)
- [x] More Assistance in footer

Department of Doing - Use same "one-stop" type-text from next steps section...
http://www.cityofgainesville.org/PlanningDepartment.aspx

Research & Plan Your Business
https://business.usa.gov/

Connect With Local Economic Development Assistance
http://www.cityofgainesville.org/EconomicDevelopmentandInnovation.aspx

**Comment by samanthawolfe** [comment]
- [ ] More Assistance in footer

Department of Doing - Use same "one-stop" type-text from next steps section...
http://www.cityofgainesville.org/PlanningDepartment.aspx

Research & Plan Your Business
https://business.usa.gov/

Connect With Local Economic Development Assistance
http://www.cityofgainesville.org/EconomicDevelopmentandInnovation.aspx

**Comment by hollymariegibbs** [comment]
@samanthawolfe Can you provide me with the city logo as a transparent PNG please? Also is the teal color correct? Just want to double check.

**Comment by samanthawolfe** [comment]
Yes, it is a teal-ish color. Feel free to use it in a black & white version if that fits best. I've requested a transparent version.

**Comment by samanthawolfe** [comment]
![ideo blue city gnv_logo](https://cloud.githubusercontent.com/assets/19419412/20937233/08c6c54a-bbb4-11e6-8271-c285d2b5b9a1.png)

**Comment by hollymariegibbs** [comment]
cc @ajcrites

**Comment by ajcrites** [comment]
I believe this is done: http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/#/steps/1
