### ISSUE TITLE
As a user, when I input text into the search bar I want to see a list of business types and permits related to my search

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#33]
This is a simple tag/word based search, such that a single word/tag match from the search text field will display a business type or permit related to that word/tag.

**Comment by Bjorn248** [comment]
* Should search all available fields (title, categories, description, etc).
* Results should show the name and link to any permit that include a search match.

**Comment by Bjorn248** [comment]
Search is half-functional right now thanks to #117, however, we still need to implement permit search.

We also need to talk through the UX for that. It's really not clear right now.

**Comment by Bjorn248** [comment]
@hollymariegibbs perhaps during the next meeting we can talk about this issue and how permit search will work?

**Comment by gotoplanb** [comment]
We're only going to support "search by business" for the initial release. 🔨
