### ISSUE TITLE
Remove unused components

### ISSUE THREAD

**Issue by jgardner34** [codegnv/business-web#35]
There's still some code shrapnel from the starter template that needs to be removed.

**Comment by Bjorn248** [comment]
Is this addressed by #45?

**Comment by ajcrites** [comment]
#56 should complete this.

**Comment by jgardner34** [comment]
This looks good now

**Comment by Bjorn248** [comment]
Looks like we've still got some extra node modules. I'll submit a PR shortly.

**Comment by Bjorn248** [comment]
Resolved
