### ISSUE TITLE
Style body

### ISSUE THREAD

**Issue by ghost** [codegnv/business-web#37]
Refer to comps:
https://www.dropbox.com/s/b4vcpak4dvqjux8/Home.png?dl=0
https://www.dropbox.com/s/86f7walarvqrp2a/Search%20Results.png?dl=0

**Comment by Bjorn248** [comment]
@hollymariegibbs I think I'm ready to at least add the button links to view/download the permits. Are these image assets somewhere or are they yet to be made? Or should I make them? Forgive me I'm new to this.

**Comment by Bjorn248** [comment]
SVGs for reference
https://www.dropbox.com/s/2pvkt6sbci0rts7/noun_831983.svg?dl=0

https://www.dropbox.com/s/3s16ubumas6suny/noun_836283.svg?dl=0

**Comment by Bjorn248** [comment]
This might be completed thanks to @firoze. Thoughts on completion status @hollymariegibbs?

**Comment by hollymariegibbs** [comment]
How do I view the current state of things?

**Comment by Bjorn248** [comment]
@hollymariegibbs http://bdev.c4gnv.com.s3-website-us-east-1.amazonaws.com/

**Comment by Bjorn248** [comment]
@hollymariegibbs said we could close this ^_^
