### ISSUE TITLE
Style footer

### ISSUE THREAD

**Issue by ghost** [codegnv/business-web#38]
Refer to comps:
https://www.dropbox.com/s/b4vcpak4dvqjux8/Home.png?dl=0
https://www.dropbox.com/s/86f7walarvqrp2a/Search%20Results.png?dl=0

**Comment by hollymariegibbs** [comment]
Specs are here: https://www.dropbox.com/sh/fcm6w8d2rkrct64/AACyIGU8wq2LC5Sd8MSAzo_ua?dl=0

Holler if anything is janky

**Comment by hollymariegibbs** [comment]
Links:

ABOUT THIS SITE
- Code for Gainesville: http://c4gnv.com/
- Code for America: https://www.codeforamerica.org/
- City of Gainesville: http://www.cityofgainesville.org

GET ASSISTANCE
- Department of Doing: **No link yet**
- Business USA: https://business.usa.gov/
- Center for Innovation & Economic Development: http://www.sfcollege.edu/cied/
- Gainesville Technology Entrepreneurship Center: http://www.sfcollege.edu/cied/incubator/index.php?section=gtec
- Center for Entrepreneurship & Innovation: http://warrington.ufl.edu/centers/cei/
- Small Business Development Center: https://www.sba.gov/tools/local-assistance/sbdc
- SCORE: https://www.score.org
- Gainesville Enterprise Zone Map: http://www.cityofgainesville.org/Portals/0/plan/docs/GIS_Enterprise_Zone.pdf
- Gainesville Innovation Zone: http://www.cityofgainesville.org/EconomicDevelopmentandInnovation/InnovationEconomy.aspx
- SBA Loan Program: https://www.sba.gov/loans-grants/see-what-sba-offers/sba-loan-programs

THIRD COLUMN
- Github: https://github.com/c4gnv/business-web/
- contribution guidelines: https://github.com/c4gnv/business-web/blob/develop/CONTRIBUTING.md
- Disclaimer: **?**
- Privacy Policy: **?**
- Accessibility: **?**

Maybe @gotoplanb or @samanthawolfe can direct you to the Department of Doing, Disclaimer, Privacy Policy and Accessibility links?

**Comment by ajcrites** [comment]
In progress on the footer branch. Will await to complete when I get the remaining links.

**Comment by Bjorn248** [comment]
Continued in #112
