### ISSUE TITLE
Create AWS Account for Hosting

### ISSUE THREAD

**Issue by Bjorn248** [codegnv/business-web#51]
Need an S3 bucket for the website and for static assets. This is not a free service, but it is very cheap ~$0.03/month for the amount of data we will be storing.

**Comment by Bjorn248** [comment]
Will have to coordinate with the city employees to figure out billing.

**Comment by samanthawolfe** [comment]
@Bjorn248 Per our last convo, is the first comment what is still needed from our end?

**Comment by Bjorn248** [comment]
@samanthawolfe for now we're using my AWS account. I still have credits on there so I'm not paying anything, but for "production launch" I'd like for it to be something that you guys are more involved with. [aws.amazon.com/free](aws.amazon.com/free) should get you started. Have you had a chance to look at the S3 hosted site? The URL is in the README of the repo now, which is displayed on the github repo home page.

**Comment by samanthawolfe** [comment]
This is in process. I'll let you know of any additional info needed from our IT. Yes, I've reviewed the site and have a few questions & comments. Should I post here @Bjorn248 or create an issue?

**Comment by Bjorn248** [comment]
Unless the comment is related to AWS Account creation you should create another issue.

**Comment by samanthawolfe** [comment]
This has been established @Bjorn248. What additional info do you need and where should I place it?

**Comment by Bjorn248** [comment]
Can you shoot me an email with my own credentials to log in? bjorn248@gmail.com

**Comment by samanthawolfe** [comment]
Do you need access to the AWS Management Console or just programmatic access?

**Comment by samanthawolfe** [comment]
![image](https://cloud.githubusercontent.com/assets/19419412/20937443/067bff5c-bbb5-11e6-80c2-6844ff5db60a.png)

**Comment by Bjorn248** [comment]
Both would be ideal. I would like the ability to create new users for API access in addition to using the console to monitor the state of things.

**Comment by samanthawolfe** [comment]
Sent to your email.

**Comment by Bjorn248** [comment]
Once we get the permissions issue resolved we can close this. Almost there :)

**Comment by Bjorn248** [comment]
@samanthawolfe we're using your AWS account now! Migration complete. I'll close this ticket now.
