### ISSUE TITLE
Search does not do anything!

### ISSUE THREAD

**Issue by moqri** [codegnv/business-web#52]
## Steps to Reproduce
1. Follow the setup instruction 
2. npm start
3. open http://localhost:8080/
4. type "retail" in the search box
5. press enter

## Expected Behavior
Showing some results or logging something on the browser console

## Actual Behavior
Nothing happens!

**Comment by moqri** [comment]
Installation warnings:
npm WARN angular2-in-memory-web-api@0.0.21 requires a peer of reflect-metadata@^0.1.3 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.21 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.1.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/router@3.1.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.1.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.

OS: OS X El Capitan

**Comment by moqri** [comment]
npm start error messages:
ERROR in business-web/node_modules/rxjs/observable/dom/AjaxObservable.d.ts
(1,1): error TS2688: Cannot find type definition file for 'chai'.

ERROR in business-web/node_modules/rxjs/observable/PairsObservable.d.ts
(1,1): error TS2688: Cannot find type definition file for 'chai'.

Fixed this errors using https://github.com/apollostack/apollo-client/issues/725 but still the search function does not do anything!

**Comment by Bjorn248** [comment]
Thanks for the report! I do believe the search function has not been implemented yet, so for now, this is behaving as expected. #33 should track its implementation.

**Comment by ajcrites** [comment]
Closing. This will be addressed by #33
