### ISSUE TITLE
Unclear "Category"

### ISSUE THREAD

**Issue by crisman** [codegnv/business-web#78]
## Steps to Reproduce

1. On front page
2. Looking for electrical permit
3. Be confused about what category I should look in, where is the building permit category?

## Expected Behavior

"Filter by Business Category" or "Filter by Business Type"

## Actual Behavior

"Filter by Category" is not clear on what category domain we are in.

**Comment by crisman** [comment]
Also above the search box "filtering by type" is unclear on what "type" means.

**Comment by Bjorn248** [comment]
Agreed. The language should be made more precise. Business type and category are completely arbitrary terms that we just stole from the [SF permit locator ](https://businessportal.sfgov.org/permits-licenses). Let's talk about how we can make this more clear for the end user.

**Comment by samanthawolfe** [comment]
Can we add another option to filter by permit?

**Comment by Bjorn248** [comment]
Sure, we can do anything, just need to flesh out the details with our experience designer @hollymariegibbs. I like the idea of giving people options when browsing the permits.

**Comment by Bjorn248** [comment]
This should be resolved by #113
